In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

<font color="red" size="6">ch14. 웹데이터 수집</font>
<!-- # <span style="color:red">ch14. 웹데이터 수집</span> -->
# 1절. BeautifulSoup과 parser
    (정적 웹크롤링, 공공api사용)
    
`pip install bs4` 아나콘다를 설치하면 자동 설치되는 패키지에 포함
- 공식사이트 : https://www.crummy.com/software/BeautifulSoup/
- documentation : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [2]:
import requests #HTTP 요청 처리하는 lib
#file:// ==c:
#http://www.
from requests_file import FileAdapter

In [3]:
# 로컬에 있는 파일을 웹요청하듯이 읽어오는 작업
s = requests.Session()
s.mount("file://",FileAdapter()) #file://로 시작하는 url을 어뎁터가 처리
response = s.get("file:///ai/source/01_python/data/ch14_sample.html")# c:/ai/lecNote/data/ch14_sample.html
response

In [4]:
%ls "C:\ai\source\01_python\data"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 0C81-36F7

 C:\ai\source\01_python\data 디렉터리

2026-07-24  오전 11:45    <DIR>          .
2026-08-12  오후 06:02    <DIR>          ..
2026-07-23  오후 07:25    <DIR>          .ipynb_checkpoints
2026-07-21  오전 09:29           221,370 0722_예제1_아파트분양가분석.docx
2026-07-07  오후 04:52                32 ch08.txt
2026-07-08  오후 06:36                84 ch09.txt
2026-07-09  오후 05:53               210 ch09_customers.txt
2026-07-09  오후 02:35         1,069,192 ch09_iris.h5
2026-07-08  오후 05:59               281 ch09_member.pkl
2025-04-21  오후 09:06               161 ch09_member.txt
2024-11-18  오후 02:56               170 ch09_member1.csv
2026-07-09  오후 12:48               327 ch09_member1.json
2024-11-18  오후 04:51               131 ch09_member1-cp.csv
2026-07-09  오후 12:47               273 ch09_member2.json
2026-07-09  오전 10:50               128 ch09_member2-write-cp.csv
2024-11-18  오후 04:27               159 ch09_member3.csv
2026-07-09  오전 11:44               180 ch09_member4.csv
2026-07-10  오후 12:44               209 ch10.pkl
2026-07-10  오후 12:47               188 ch11.npy
2026-07-15  오후 12:39             4,009 ch11_iris.csv
2026-07-15  오후 12:39               976 ch11_iris.zip
2025-04-28  오후 04:53               361 ch11_member.csv
2024-11-25  오후 03:22               312 ch11_membercp949.csv
2024-11-25  오후 03:19               361 ch11_membersep.csv
2024-11-25  오후 03:21               361 ch11_membertab.csv
2026-07-24  오후 06:34            63,357 ch12_plot.png
2026-07-23  오후 07:25           848,656 ch13_연습포트폴리오_아파트분양가분석.ipynb
2026-07-23  오전 10:52           690,589 ch13_예1_포트폴리오_아파트분양가분석_원본.ipynb
2025-11-09  오후 06:59               528 ch14_sample.html
2026-07-23  오후 06:00            59,709 df(최종).csv
2026-07-24  오전 09:35           394,458 df_last.csv
2026-07-08  오후 06:39               126 ex.txt
2026-07-08  오후 06:42               163 exex.txt
2026-07-07  오후 04:52                39 test.txt
2026-06-24  오후 10:04             2,163 전국 평균 평당 분양가격(2013년 9월부터 2015년 8월까지).csv
2026-07-14  오후 05:35           501,367 주택도시보증공사_전국 신규 민간아파트 분양가격 동향_20260531.csv
              33개 파일           3,860,630 바이트
               3개 디렉터리  115,177,078,784 바이트 남음

In [5]:
if response:
    print('해당 url에 접근함')
else:
    print('해당 url에 거부됨')

해당 url에 접근함

In [6]:
response.status_code
#200 : 정상
#404 : 없는 패이지

200

In [7]:
response.content #html의 바이너리 형식

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [8]:
print(response.content.decode('utf-8'))

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [9]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [10]:
#html 파싱 객체
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text,#response.content,
                    "html.parser")
# soup

In [11]:
#soup.select_one('선택자') : 해당 선택자 처음 하나 엘리먼트만
el = soup.select_one('h1.greeting.css')
print('el=',el)
print('el.text=>',el.text)
print('el.string=>',el.string)
print('el의 속성들=>',el.attrs)
print('el의 class속성=>',el.attrs['class'])
print('el의 class속성=>',el.attrs.get('class'))
#print('el의 href속성(없는 속성은 에러)=>',el.attrs.get['href'])
print('el의 href속성(없는 속성은 에러)=>',el.attrs.get('href'))

el= <h1 class="greeting css" id="text">Hello, CSS</h1>
el.text=> Hello, CSS
el.string=> Hello, CSS
el의 속성들=> {'class': ['greeting', 'css'], 'id': 'text'}
el의 class속성=> ['greeting', 'css']
el의 class속성=> ['greeting', 'css']
el의 href속성(없는 속성은 에러)=> None

In [12]:
# 2. soup.select('선택자') : 해당 선택자 엘리먼트 다 배열로
els=soup.select('h1.css')
print('el=>',els)
print('els들의 text',[el.text for el in els])
print('els들의 string',[el.string for el in els])
print('els들의 속성들',[el.attrs for el in els])
print('els들의 class 속성',[el.attrs.get('class') for el in els])

el=> [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els들의 text ['Hello, CSS', 'Hi, CSS']
els들의 string ['Hello, CSS', 'Hi, CSS']
els들의 속성들 [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els들의 class 속성 [['greeting', 'css'], ['css']]

In [13]:
# 3.soup.find(태그,속성) vs soup.select_one('선택자'):해당 속성을 가진 태그 처음 하나만
print('select_one:',soup.select_one('h1.css'))
print('find      :',soup.find('h1',{'class':'css'}))
print('find      :',soup.find('h1',class_='css'))
print()
print('select_one:',soup.select_one('h1#text'))
print('select_one:',soup.find('h1',{'id':'text'}))

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>

In [14]:
# 4.soup.find_all(태그,속성) vs soup.select_one('선택자'):해당 엘리먼트 다 list로
print('모든 h1.css.greeting와 span태그:',soup.select('h1.css.greeting,span'))
print('모든 h1.css.greeting와 span태그:',soup.find_all(['h1'],class_='css')+
                                        soup.find_all('span'))

모든 h1.css.greeting와 span태그: [<h1 class="greeting css" id="text">Hello, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css.greeting와 span태그: [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]

In [15]:
# 없는 엘리먼트 찾기
print('find_all(빈list):',soup.find_all('a'))
print('find(None)     :',soup.find('a'))
print('select(빈list):',soup.select('a'))
print('select_one(None):',soup.select_one('a'))

find_all(빈list): []
find(None)     : None
select(빈list): []
select_one(None): None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
## 2.1BeautifulSoup 모듈을 활용한 html웹 데이터 수집
### 1)환율정보 가져오기(네이버 증권>시장지표)

-https://finance.naver.com/marketindex/

    * 크롤링 허용범위는 사이트 마다~/robots.txt에서 확인할수있음
        -Allow : 크롤링 허용가능한 폴더
        -Disallow : 크롤링 제한 폴더

In [16]:
# soup객체 생성 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
response #Response
print(response.status_code)
# print(response.text)#response.content
soup = BeautifulSoup(response.text,'html.parser')

200

In [17]:
# soup객체 생성 방법2
from urllib.request import urlopen
url = 'https://finance.naver.com/marketindex/'
response = urlopen(url)
#response # HTTPResponse
print(response.status)
#print(response.read().decode('cp949'))
soup = BeautifulSoup(response,'html.parser')

200

In [18]:
p='1,417.70'
float(p.replace(',',''))#방법1
float(''.join(p.split(',')))#방법2

1417.7

In [19]:
# div.head_info 밑의 span.value(find계열)
prices=[]
headinfos = soup.find_all('div',class_='head_info')
for headinfo in headinfos:
    #print(headinfo)
    price = headinfo.find('span',class_='value')
    prices.append(float(''.join(price.text.split(','))))
print(prices)

[1411.9, 886.2, 1627.92, 209.38, 159.23, 1.1541, 1.3508, 99.89, 83.27, 1863.64, 4467.5, 201114.68]

In [20]:
# span.value(find 계열)
price_els = soup.find_all('span',class_='value')
prices = [float(price.text.replace(',',''))for price in price_els]
print(prices)

[1411.9, 886.2, 1627.92, 209.38, 159.23, 1.1541, 1.3508, 99.89, 83.27, 1863.64, 4467.5, 201114.68]

In [21]:
# 금액들 div.head_info 밑의 span.value
price_els = soup.select('div.head_info>span.value')
#price_els

In [22]:
#타이틀
title_els = soup.select('h3.h_lst>span.blind')
title_els

[<span class="blind">미국 USD</span>,
 <span class="blind">일본 JPY(100엔)</span>,
 <span class="blind">유럽연합 EUR</span>,
 <span class="blind">중국 CNY</span>,
 <span class="blind">달러/일본 엔</span>,
 <span class="blind">유로/달러</span>,
 <span class="blind">영국 파운드/달러</span>,
 <span class="blind">달러인덱스</span>,
 <span class="blind">WTI</span>,
 <span class="blind">휘발유</span>,
 <span class="blind">국제 금</span>,
 <span class="blind">국내 금</span>]

In [23]:
#단위들 : div.head_info span blind
unit_els = soup.select('div.head_info>span>span.blind')
len(unit_els)
units=[unit_el.string for unit_el in unit_els]
units.insert(7,'')
units

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [24]:
trend_els = soup.select('div.head_info>span.blind')

In [25]:
for title,price,unit,trend in zip(title_els, price_els, units,trend_els):
    print("{}:{} {}-{}".format(title.text,price.text,unit,trend.text))

미국 USD:1,411.90 원-하락
일본 JPY(100엔):886.20 원-하락
유럽연합 EUR:1,627.92 원-하락
중국 CNY:209.38 원-하락
달러/일본 엔:159.2300 엔-하락
유로/달러:1.1541 달러-보합
영국 파운드/달러:1.3508 달러-상승
달러인덱스:99.8900 -상승
WTI:83.27 달러-상승
휘발유:1863.64 원-하락
국제 금:4467.5 달러-상승
국내 금:201114.68 원-상승

In [26]:
import pandas as pd
data = []
for title,price,unit,trend in zip(title_els, price_els, units,trend_els):
    data.append({'title':title.text,
                 'price':float(price.text.replace(',','')),
                 'unit' :unit,
                 'trend':trend.text})
                               
pd.DataFrame(data)#.to_csv('data/file.csv',index=False)

           title        price unit trend
0         미국 USD    1411.9000    원    하락
1   일본 JPY(100엔)     886.2000    원    하락
2       유럽연합 EUR    1627.9200    원    하락
3         중국 CNY     209.3800    원    하락
4        달러/일본 엔     159.2300    엔    하락
5          유로/달러       1.1541   달러    보합
6      영국 파운드/달러       1.3508   달러    상승
7          달러인덱스      99.8900         상승
8            WTI      83.2700   달러    상승
9            휘발유    1863.6400    원    하락
10          국제 금    4467.5000   달러    상승
11          국내 금  201114.6800    원    상승

In [27]:
data = []
for title,price,unit,trend in zip(title_els, price_els, units,trend_els):
    data.append([title.text,float(price.text.replace(',','')),unit,trend.text])
pd.DataFrame(data,columns=['title','price','unit','trend'])

           title        price unit trend
0         미국 USD    1411.9000    원    하락
1   일본 JPY(100엔)     886.2000    원    하락
2       유럽연합 EUR    1627.9200    원    하락
3         중국 CNY     209.3800    원    하락
4        달러/일본 엔     159.2300    엔    하락
5          유로/달러       1.1541   달러    보합
6      영국 파운드/달러       1.3508   달러    상승
7          달러인덱스      99.8900         상승
8            WTI      83.2700   달러    상승
9            휘발유    1863.6400    원    하락
10          국제 금    4467.5000   달러    상승
11          국내 금  201114.6800    원    상승

### 2)이번주 로또번호 출력
- 방법2에서 UserAgent를 추가하여 soup생성
- https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto(다음에서 lotto검색)
```
    1236회(2026.08.08 추첨)
    당첨번호 [12,18,21,29,34,38]
    보너스 10
```

In [28]:
# 방법1
import requests
from bs4 import BeautifulSoup
url ='https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
response = requests.get(url)
print('response의 상태:',response.status_code)
soup = BeautifulSoup(response.text,'html.parser')
#soup

response의 상태: 200

In [29]:
# 방법2
from urllib.request import urlopen, Request
headers = {'User-Agent':
           'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}       
request =Request(url,headers=headers)

response =urlopen(request)
print('response의 상태:',response.status)
soup = BeautifulSoup(response,'html.parser')
#soup

response의 상태: 200

In [30]:
#1236회(2026.08.08 추첨)
# 당첨번호 [12, 18, 21, 29, 34, 38]
# 보너스 10
times = soup.select_one('div.prize  span.f_red').text
date = soup.select_one('div.prize > span.date').text
title1 = soup.select_one('div.prize > strong').text[-4:]
lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
title2 = soup.select_one('div.lottonum span.screen_out').text
bonus_number = soup.select_one('div.lottonum > span.bg_ball1').text
print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

In [31]:
# 위의 select계열 함수를 find계열함수로 변경하여 구현해보기
#times = soup.select_one('div.prize  span.f_red').text
prize = soup.find('div',class_='prize')
times = prize.find('span',class_='f_red').text
#date = soup.select_one('div.prize > span.date').text
date = prize.find('span', class_='date').text
#title1 = soup.select_one('div.prize > strong').text[-4:]
title1 = prize.find('strong').text[-4:]
#lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
lottonum = soup.find('div', class_='lottonum')
#lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
lotto_numbers = lottonum.find_all('span', class_='ball')[:-2]

#title2 = soup.select_one('div.lottonum span.screen_out').text
title2 = lottonum.find('span', class_='screen_out').text

#bonus_number = soup.select_one('div.lottonum > span.bg_ball1').text
bonus_number = lottonum.find('span', class_='bg_ball1').text
print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

### 3)다음 뉴스 검색 리스트
```
no title  href
0 타이틀1  http://~
1 타이틀2  http://~ 
2 타이틀3  http://~
```

In [32]:
# 방법1
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = f'https://search.daum.net/search?w=news&q={word}'
print(url)
response = requests.get(url)
print(response.status_code)
soup = BeautifulSoup(response.text,'html.parser')

https://search.daum.net/search?w=news&q=비트코인
200

In [33]:
#방법2
from urllib.request import urlopen,Request
from urllib.parse import quote
word = quote('비트코인')
url = f'https://search.daum.net/search?w=news&q={word}'
headers = {'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request = Request(url)
request.add_header('User-Agent',
                  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
response = urlopen(request)
print(response.status)
soup = BeautifulSoup(response,'html.parser')
#soup

200

In [34]:
items_find_list = []
items_el = soup.select('div.item-title>strong.tit-g >a')
for idx, item in enumerate(items_el):
    #print(idx,item.attrs['href'])
    items_find_list.append({'no':idx,
                            'title':item.text,
                            'link':item.attrs.get('href')})
import pandas as pd
pd.DataFrame(items_find_list)

Empty DataFrame
Columns: []
Index: []

In [35]:
items_find_list = []
items_el = soup.select('div.item-title>strong.tit-g >a')
for idx,item in enumerate(items_el):
    items_find_list.append([idx,item.text,item.attrs.get('href')])
pd.DataFrame(items_find_list,columns=['순번','기사제목','링크'])

Empty DataFrame
Columns: [순번, 기사제목, 링크]
Index: []

In [59]:
# 다음 뉴스 검색 함수(원하는 키워드, 원하는 패이지로)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
def collect_list(keyword,page):
    'keyword로 해당 page에 검색한 결과 return'
    #url = https://search.daum.net/search?w=news&q={keyword}&enc=utf8&cluster=y&cluster_page=1&DA=PGD&p={page}
    url = 'https://search.daum.net/search?w=news&enc=utf8&cluster=y&cluster_page=1&DA=PGD'
    params = {'q':keyword,'p':page}
    response = requests.get(url,params=params)
    soup = BeautifulSoup(response.text,'html.parser')
    items_find_list = []
    items_el = soup.select('div.item-title>strong.tit-g >a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10 + idx,
                                'title':item.text,
                                'link': item.attrs.get('href')})
    return items_find_list

In [60]:
collect_list('배이스볼',2)

[{'no': 10,
  'title': ' 광주충장중 충장베이스볼클럽, 광주 중학교 야구대회 역전 우승 ',
  'link': 'http://v.daum.net/v/20260811125307330'},
 {'no': 11,
  'title': ' "이 카드 주면 32년치 프리미엄 시즌권 드립니다" NBA 구단이 내건 초대박 조건... 결국 \'세계 단 1장\' 나왔다 ',
  'link': 'http://v.daum.net/v/20260812055137409'},
 {'no': 12,
  'title': ' “경기 수 줄여야한다”라던 김태형 롯데 감독의 속뜻은 “국제 경기가 많다…감독이 대신 말해주는 것” ',
  'link': 'http://v.daum.net/v/20260812134809263'},
 {'no': 13,
  'title': ' \'포브스 선정\' 슈퍼팀 LAD에 도전할 유일한 팀 ATL, 그런데 김하성의 이름은? "벤치 멤버"…대권 도전에 끝까지 동참할 수 있을까 ',
  'link': 'http://v.daum.net/v/20260812011648082'},
 {'no': 14,
  'title': " 한국계 메이저리거 '은퇴 소식' 나왔다, 이대로 태극마크 못 달고 현역 생활 마무리? '89억 계약→1년 못 넘기고 방출' 결국 유니폼 벗나 ",
  'link': 'http://v.daum.net/v/20260811180209383'},
 {'no': 15,
  'title': ' 롯데 김태형 감독 "144경기 많다는 뜻 아냐…국제대회 겹친 일정이 빡빡한 것" ',
  'link': 'http://v.daum.net/v/20260811183002417'},
 {'no': 16,
  'title': " '어머니의 나라'에서 뛸 수 있나? 'WBC 8강 주역' 위트컴 방출 위기...KBO에서 관심 가질까 ",
  'link': 'http://v.daum.net/v/20260811153939124'},
 {'no': 17,
  'title': ' 아시안게임 야구대표팀 9월 14일 소집·이틀 훈련하고 일본으로 ',
  'link': 'http://v.daum.net/v/20260812165030309'},
 {'no': 18,
  'title': ' “이상기후·국제대회 늘어난다” 김태형 작심발언…왜 KBO 144G 많다고 발언했나 ',
  'link': 'http://v.daum.net/v/20260812054053312'},
 {'no': 19,
  'title': " [오피셜] 이럴수가! 35홈런 '한국계 거포' 어쩌다 이렇게 됐나…타율 0.130 충격 부진→40인 로스터 제외, 방출 위기 ",
  'link': 'http://v.daum.net/v/20260811154246280'}]

In [61]:
result = [] #해당 키워드 원하는 패이지 수만큼 검색한 결과를 담을 변수 dict리스트
pages = 3
for page in range(1,pages+1):
    print(f'=={page}패이지 수집중==')
    item_result = collect_list('추석열차',page)
    result.append(item_result)
    time.sleep(3)
pd.DataFrame(result).to_csv('data/ch14_추석열차.csv',index=False)

==1패이지 수집중==
==2패이지 수집중==
==3패이지 수집중==

In [51]:
r = []
r.extend([1,2,3])
r.extend([4,5,6])
r

[1, 2, 3, 4, 5, 6]

In [63]:
keywords = ['김혜수','영화']
pages = 3
result0 = []
result1 = []
for i, keyword in enumerate(keywords):
    print(f'= ={i+1}번째 검색어{keyword}검색 결과 수집({page}패이지)중입니다= =')
    for page in range(1,pages+1):
        if i==0:
            result0.extend(collect_list(keyword,page))
        else:
            result1.extend(collect_list(keyword,page))
        time.sleep(3)

= =1번째 검색어김혜수검색 결과 수집(3패이지)중입니다= =
= =2번째 검색어영화검색 결과 수집(3패이지)중입니다= =

In [ ]:
result0_df = pd.DataFrame(result0)
result1_df = pd.DataFrame(result1)

In [64]:
result0_df.to_csv(f'data/ch14_{keywords[0]}.csv',index=False,encoding='cp949')
result1_df.to_csv(f'data/ch14_{keywords[0]}.csv',index=False,encoding='cp949')

NameError: name 'result0_df' is not defined

### 4)User-Agent를 추가하여 크롤링
- request.get(url),urlopen(url)함수를 사용하면 크롤링이 막혀있는 사이트
- 방법2에서 User-Agent를 추가하여 크롤링

- https://www.melon.com/robot.txt에서 일부 경로는 User-Agent에 봇이 지정

In [68]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
melonResponse = requests.get(url)
print(melonResponse.status_code)
soup = BeautifulSoup(melonResponse.text,'html.parser')
soup

406

In [69]:
# User-Agent를 추가하여 방법2
from urllib.request import urlopen
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
headers={'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
melonpage = Request(url,headers=headers)
melonpage = Request(url)
melonpage.add_header('User-Agent',
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
melonResponse = urlopen(melonpage)
print(melonResponse.status)
soup = BeautifulSoup(melonResponse,'html.parser')
#soup

200

In [98]:
# User-Agent를 추가하여 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://www.melon.com/chart/'
headers={'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
melonResponse = requests.get(url,headers=headers)
print(melonResponse.status_code)
soup = BeautifulSoup(melonResponse.text,'html.parser')
#soup

200

In [107]:
# 1위 : LOVE ATTACK / RESCENE (리센느)의 url{}
# 순위, 곡명, 가수, 가수페이지
rank_els = soup.select('div.wrap.t_center>span.rank')[1:]#맨앞엔 '순위'
ranks=[rank.text for rank in rank_els]

title_els = soup.select('div.ellipsis.rank01 >span')
titles=[title.text for title in title_els]

singer_els = soup.select('span.checkEllipsis') #40위, 90위 가수가 복수명
singers=[singer.text.replace('/xa0','') for singer in singer_els]

links=[]
for singer_el in singer_els:
    #print(singer_el)
    singer_link = 'https://www.melon.com/'+ singer_el.find('a').attrs.get('href')
    links.append(singer_link)
print(len(ranks), len(titles), len(singers), len(links))

# for idx,(title,singer,link) in enumerate(zip(titles,singers,links)):
#     print("{}위.{}|{}".format(idx+1,title,singer))
melon_chat_list = []
for rank,title, singer, link in zip(ranks,titles,singers,links):
    #print(f'{rank}위{title}|{singer}')
    melon_chat_list.append({
        '순위':rank,
        '곡명':title,
        '가수':singer,
        '가수패이지':link
    })
pd.DataFrame(melon_chat_list)

100 100 100 100

,순위,곡명,가수,가수패이지
0,1,\nLOVE ATTACK\n,RESCENE (리센느),https://www.melon.com//artist/detail.htm?artis...
1,2,\n갑자기\n,아이오아이 (I.O.I),https://www.melon.com//artist/detail.htm?artis...
2,3,\nREDRED\n,CORTIS (코르티스),https://www.melon.com//artist/detail.htm?artis...
3,4,\nLEMONADE\n,aespa,https://www.melon.com//artist/detail.htm?artis...
4,5,\nPretty Girl\n,RESCENE (리센느),https://www.melon.com//artist/detail.htm?artis...
...,...,...,...,...
95,96,\nFOCUS\n,Hearts2Hearts (하츠투하츠),https://www.melon.com//artist/detail.htm?artis...
96,97,\nHooligan\n,방탄소년단,https://www.melon.com//artist/detail.htm?artis...
97,98,\n2.0\n,방탄소년단,https://www.melon.com//artist/detail.htm?artis...
98,99,\nSoda Pop\n,"KPop Demon Hunters Cast, Danny Chung, Saja Boy...",https://www.melon.com//artist/detail.htm?artis...
99,100,\nOVERDRIVE\n,TWS (투어스),https://www.melon.com//artist/detail.htm?artis...

### 5) 네이버 지식인 검색(Open API 사용X)
- 특정 keyword를 특정 페이지 수만큼

In [109]:
#방법1
from requests import get
from bs4 import BeautifulSoup
keyword = "grok"
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
print(url)
response = get(url)
print(response.status_code)
soup = BeautifulSoup(response.text,'html.parser')

https://kin.naver.com/search/list.naver?query=grok
200

In [110]:
#방법2
from urllib.request import urlopen
from bs4 import BeautifulSoup
from urllib.parse import quote
keyword = quote("grok")
url = f'https://kin.naver.com/search/list.naver?query={keyword}'
print(url)
response = urlopen(url)
print(response.status)
soup = BeautifulSoup(response,'html.parser')

https://kin.naver.com/search/list.naver?query=grok
200

In [120]:
# keyword를 원하는 패이지 수만큼
from requests import get
from bs4 import BeautifulSoup
keyword = "Gemini"
pages = 3
items_list = []#크롤링한 데이터를 담을 list
for page in range(1,pages+1):
    url = f'https://kin.naver.com/search/list.naver?query={keyword}&page={page}'
#     url = 'https://kin.naver.com/search/list.naver'
#     params = {'query':keyword, 'page':page}
#     response=get(url,params=params)
    response = get(url)    
#     print(response.status_code)
    soup = BeautifulSoup(response.text,'html.parser')
    #글재목,link
    dt_els = soup.find_all('dt')
    for dt_el in dt_els:
        item = dt_el.find('a')
        items_list.append({
            'title':item.text,
            'link':item.attrs.get('href')
        })
df = pd.DataFrame(items_list)

In [121]:
df.head()

,title,link
0,삼성 브라우저 gemini 끄는 법,https://kin.naver.com/qna/detail.naver?dirId=1...
1,내일배움카드로 Gemini 공부하고 싶은데 적절....,https://kin.naver.com/qna/detail.naver?dirId=1...
2,gemini 구독 질문이여,https://kin.naver.com/qna/detail.naver?dirId=1...
3,챗GPT 답변 금지! (Gemini 등도 포함),https://kin.naver.com/qna/detail.naver?dirId=4...
4,Gemini 재미나이한테 경제대해 물어보니까...,https://kin.naver.com/qna/detail.naver?dirId=6...

## 2.2 open API사용 : json웹데이터 수집
### 1)네이버 지식인으로 검색(openAPI사용 O)

- 네이버 개발자 센터에서 애플리캐이션을 등록(id,pw)=>NAVER API HUB

In [22]:
#%pip install dotenv
%pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\admin\anaconda3\lib\site-packages (1.2.2)
Note: you may need to restart the kernel to use updated packages.

In [27]:
import os
print(os.getcwd())

C:\ai\source\01_python

SyntaxError: invalid syntax (1640342331.py, line 1)

In [1]:
# 환경변수를 쓰기 위한 패키지 : dotenv
from dotenv import load_dotenv
import os
load_dotenv(
    #dotenv_path='.env'
)
print(os.getenv('CLIENT_ID')[:3])
print(os.getenv('CLIENT_SECRET')[:3])

HPa
RN8

In [2]:
 #방법2
import os
import sys
import urllib.request
import json
import pandas as pd
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
encText = urllib.parse.quote("쳇지피티")
url = f"https://openapi.naver.com/v1/search/kin.json?query={encText}" # JSON 결과
# request = urllib.request.Request(url)
# request.add_header("X-Naver-Client-Id",client_id)
# request.add_header("X-Naver-Client-Secret",client_secret)
headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret':client_secret
}
request = urllib.request.Request(url, headers=headers)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    # print(response_body.decode('utf-8')[:30])
else:
    print("Error Code:" + rescode)

data = json.loads(response_body) # 문자를 json형태로 변환
print('data의 응답들 :', data.keys())
print('검색결과 갯수 :', len(data['items']))

items = data['items']
items_list = []
for item in items:
    #print(item)
    title = item['title'].replace('<b>','').replace('</b>','')
    link  = item['link']
    description = item['description'].replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description'])

data의 응답들 : dict_keys(['lastBuildDate', 'total', 'start', 'display', 'items'])
검색결과 갯수 : 10

,title,link,description
0,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요,https://kin.naver.com/qna/detail.naver?dirId=4...,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요. 논문제목 작성 및 논문...
1,쳇지피티로 사주 해석을 해봤는데 맞는건가요?,https://kin.naver.com/qna/detail.naver?dirId=3...,쳇지피티로 배우자가 어떤 사람인지 사주 해석을 해봤는데 맞는건가요??? 전체 흐름을...
2,쳇지피티 오류 나만 그래요?,https://kin.naver.com/qna/detail.naver?dirId=1...,짜증나네 삭제해도 안되고 왜이러는거에요 현재 쳇지피티 오류 나는거 모두 다 동일한 ...
3,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요,https://kin.naver.com/qna/detail.naver?dirId=4...,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요. 논문제목 작성 및 논문...
4,고등학교 수행평가에 쳇지피티 쓰면 안되나요?,https://kin.naver.com/qna/detail.naver?dirId=1...,쳇지피티로 쓰던데 쓰면 안되아요? 요즘 지피티 검사기도 있고 선생님들도 지피티쓴 글...
5,쳇지피티 오류,https://kin.naver.com/qna/detail.naver?dirId=1...,이거 왜이런건가요…? 한번에 너무 많은 요구를 했거나 해당 버전을 동시간대에 사용하...
6,뉴스 보다가 범죄자가 검색한 쳇 지피티 도 조회 한다고 하....,https://kin.naver.com/qna/detail.naver?dirId=6...,제미나이 이런것도 포렌식 해서 다 검열을 하나요 첨 알아서요 검색 목록만 보는줄 알...
7,쳇 지피티 운세 정확한가요?,https://kin.naver.com/qna/detail.naver?dirId=3...,쳇 지피티 운세 어느정도 정확한가요? 무료로 꽤 정확한 운세 보는 방법 있으면 알려...
8,카카오톡 쳇지피티,https://kin.naver.com/qna/detail.naver?dirId=1...,이거 사용하는거 무료인가요 ? 돈 나가요!
9,쳇지피티로 사주 해석을 해봤는데 맞는건가요?,https://kin.naver.com/qna/detail.naver?dirId=3...,쳇지피티로 배우자가 어떤 사람인지 사주 해석을 해봤는데 맞는건가요??? 안녕하세요 ...

In [3]:
import os
import requests
import json
import pandas as pd
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')
encText = "스위스"
url = f"https://openapi.naver.com/v1/search/kin.json" # JSON 결과
params = {'query':encText, 'display':20 }
headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret':client_secret
}
response = requests.get(url, params=params, headers=headers)

items = response.json()['items'] # response를 json형태로 변환한것 중 'items'
items_list = []
for item in items:
    #print(item)
    title = item['title'].replace('<b>','').replace('</b>','')
    link  = item['link']
    description = item['description'].replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description']).sample()

,title,link,description
15,스위스 패스권 조언 부탁드립니다,https://kin.naver.com/qna/detail.naver?dirId=9...,"세이버데이패스는 스위스 구간만 이용가능하니, 베네치아에서... 위에 말씀드린대로, ..."

### 2)NAVER API HUB방식으로 지식IN검색

In [4]:
# 방법1
import os
import requests
import json
import pandas as pd
from dotenv import load_dotenv
load_dotenv() # 환경 변수 load
client_id = os.getenv('NEW_CLIENT_ID')
client_secret = os.getenv('NEW_CLIENT_SECRET')
encText = "쳇지피티"
url = f"https://naverapihub.apigw.ntruss.com/search/v1/kin" # JSON 결과
params = {'query':encText, 'display':20 }
headers = {
    'X-NCP-APIGW-API-KEY-ID': client_id,
    'X-NCP-APIGW-API-KEY':client_secret
}
response = requests.get(url, params=params, headers=headers)
items = response.json()['items'] # response를 json형태로 변환한것 중 'items'
items_list = []
for item in items:
    #print(item)
    title = item['title'].replace('<b>','').replace('</b>','')
    link  = item['link']
    description = item['description'].replace('<b>','').replace('</b>','')
    items_list.append([title, link, description])
pd.DataFrame(items_list, columns=['title','link','description']).sample()

,title,link,description
0,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요,https://kin.naver.com/qna/detail.naver?dirId=4...,박사논문을 잘 쓰려면 쳇지피티 외 어떤ai하나더 추천해줘요. 논문제목 작성 및 논문...

In [5]:
def get_image_list(query):
    'query로 검색한 이미지 정보(제목, 링크,썸네일, size) 100건 데이터 프레임을 return(방법1)'
    from dotenv import load_dotenv
    import os
    import requests
    import pandas as pd
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    url = 'https://openapi.naver.com/v1/search/image'
    params = {'query':query, 'display':100 }
    response = requests.get(url, params=params, headers=headers)
    
    items = response.json()['items']
    # print(items[:2])
    items_list = []
    for item in items:
        items_list.append({
            '제목':item.get('title'),
            '링크':item.get('link'),
            '썸네일':item.get('thumbnail'),
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
    return pd.DataFrame(items_list)
get_image_list("청바지")

,제목,링크,썸네일,sizeheight,sizewidth
0,[홍은]통바지 데님 연청 여자 하이웨이스트 와이드 청바지 | 텐바이텐,https://thumbnail.10x10.co.kr/webimage/image/b...,https://search.pstatic.net/sunny/?type=b150&sr...,500,500
1,여성용 와이드 하이웨스트 데님팬츠 데일리 청바지 5516,http://shopping.phinf.naver.net/main_5712970/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
2,가을 겨울 일자핏 캐주얼 와이드 청바지 DNZK03 : 스마트 공장,http://shop1.phinf.naver.net/20241125_266/1732...,https://search.pstatic.net/common/?type=b150&s...,916,750
3,여자 스키니진 스판 타이트 청바지 | 텐바이텐,https://thumbnail.10x10.co.kr/webimage/image/b...,https://search.pstatic.net/sunny/?type=b150&sr...,500,500
4,남자 와이드 스랙스 9부 바지 가 남성 청바지 루즈한 스트레이트 리 광저우 : so...,http://shop1.phinf.naver.net/20260331_151/1774...,https://search.pstatic.net/common/?type=b150&s...,1000,750
...,...,...,...,...,...
95,MOSAIRATION 여성 청바지 하이웨스트 캐주얼 스트레이트 데님 팬츠 M0011214,http://shopping.phinf.naver.net/main_5905233/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000
96,여성 바지 빈티지 캐주얼 가을 청바지 데님바지 엘보 배기핏 와이드 워싱 데일룩 DA...,https://shop-phinf.pstatic.net/20260225_102/17...,https://search.pstatic.net/common/?type=b150&s...,500,500
97,여성 슬림핏 하이웨이스트 데님 청바지 봄 와이드 스트레이트 크롭 : 하유유통,https://shop-phinf.pstatic.net/20260605_15/178...,https://search.pstatic.net/common/?type=b150&s...,800,800
98,타미힐피거 기본 워싱 청바지 EMM3PD91A,http://shopping.phinf.naver.net/main_6623271/6...,https://search.pstatic.net/common/?type=b150&s...,500,500
99,TKX 남성 복고풍 자수 디테일 와이드 청바지 캐주얼 스타일 봄가을 워싱 편한 사진색,http://shopping.phinf.naver.net/main_5874184/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000

In [6]:
def get_image_list(query):
    'query로 검색한 이미지 정보(제목, 링크,썸네일, size) 100건 데이터 프레임을 return(방법2)'
    from dotenv import load_dotenv
    import os
    from urllib.request import urlopen, Request
    from urllib.parse import quote
    import json
    import pandas as pd
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    query = quote(query)
    url = f'https://openapi.naver.com/v1/search/image?query={query}&display=100'
    request = Request(url, headers=headers)
    response = urlopen(request)
    
    items = json.loads(response.read())['items']
    # print(items[:2])
    items_list = []
    for item in items:
        items_list.append({
            '제목':item.get('title'),
            '링크':item.get('link'),
            '썸네일':item.get('thumbnail'),
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
    return pd.DataFrame(items_list)
df = get_image_list("청바지")
df.sample()

,제목,링크,썸네일,sizeheight,sizewidth
67,AOKADA 남성 스판 데님 팬츠 봄 가을 루즈핏 일자 통 청바지,http://shopping.phinf.naver.net/main_5687128/5...,https://search.pstatic.net/common/?type=b150&s...,900,900

In [7]:
df.to_csv('data/img_list.csv', encoding='cp949', index=False)

In [8]:
# df에 있는 이미지 로컬에 저장하기
print(df.loc[1, '링크']) # 메인_01_청바지.jpg
print(df.loc[0, '썸네일']) # 썸네일_01_청바지.jpg

http://shopping.phinf.naver.net/main_5712970/57129708867.20251008173842.jpg
https://search.pstatic.net/sunny/?type=b150&src=https%3A%2F%2Fthumbnail.10x10.co.kr%2Fwebimage%2Fimage%2Fbasic600%2F741%2FB007415375.jpg%3Fcmd%3Dthumb%26w%3D500%26h%3D500%26fit%3Dtrue%26ws%3Dfalse

In [9]:
def save_image(attr, idx, link, query):
    'link의 이미지를 image/attr_idx_query.확장자로 local에 저장'
    import requests
    file_extension = link.split('.')[-1]
    index = file_extension.find('?') # 확장자 뒤에 ?가 있는 위치(?가 없으면 -1)
    if index != -1:
        file_extension = file_extension[:index] # 물음표앞까지만 확장자로 
    img = requests.get(link).content # link요청을 바이너리
    with open(f'image/{attr}_{idx:02}_{query}.{file_extension}', 'wb') as f:
        f.write(img) # 파일 저장
save_image('썸네일', 0, df.loc[0,'썸네일'], '청바지')

In [10]:
import pandas as pd
df = pd.read_csv('data/img_list.csv', encoding='cp949')

In [19]:
dff = df[df['링크'].str.find('?')==-1]
d

NameError: name 'df' is not defined

### quiz) 네이버 open API를 이용하여 원하는 query 이미지 100건의데이터를 'data/img_list.csv'파일로
- title(제목), link(링크), thumbnail(썸네일), sizeheight, sizewidth

In [37]:
def get_image_list(query):
    'query로 검색한 이미지 정보(제목, 링크,썸네일, size) 100건 데이터 프레임을 return(방법1)'
    from dotenv import load_dotenv
    import os
    import requests
    import pandas as pd
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    url = 'https://openapi.naver.com/v1/search/image'
    params = {'query':query, 'display':100 }
    response = requests.get(url, params=params, headers=headers)
    
    items = response.json()['items']
    # print(items[:2])
    items_list = []
    for item in items:
        items_list.append({
            '제목':item.get('title'),
            '링크':item.get('link'),
            '썸네일':item.get('thumbnail'),
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
    return pd.DataFrame(items_list)
get_image_list("청바지")

,제목,링크,썸네일,sizeheight,sizewidth
0,[홍은]통바지 데님 연청 여자 하이웨이스트 와이드 청바지 | 텐바이텐,https://thumbnail.10x10.co.kr/webimage/image/b...,https://search.pstatic.net/sunny/?type=b150&sr...,500,500
1,여성용 와이드 하이웨스트 데님팬츠 데일리 청바지 5516,http://shopping.phinf.naver.net/main_5712970/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
2,가을 겨울 일자핏 캐주얼 와이드 청바지 DNZK03 : 스마트 공장,http://shop1.phinf.naver.net/20241125_266/1732...,https://search.pstatic.net/common/?type=b150&s...,916,750
3,여자 스키니진 스판 타이트 청바지 | 텐바이텐,https://thumbnail.10x10.co.kr/webimage/image/b...,https://search.pstatic.net/sunny/?type=b150&sr...,500,500
4,남자 와이드 스랙스 9부 바지 가 남성 청바지 루즈한 스트레이트 리 광저우 : so...,http://shop1.phinf.naver.net/20260331_151/1774...,https://search.pstatic.net/common/?type=b150&s...,1000,750
...,...,...,...,...,...
95,MOSAIRATION 여성 청바지 하이웨스트 캐주얼 스트레이트 데님 팬츠 M0011214,http://shopping.phinf.naver.net/main_5905233/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000
96,여성 바지 빈티지 캐주얼 가을 청바지 데님바지 엘보 배기핏 와이드 워싱 데일룩 DA...,https://shop-phinf.pstatic.net/20260225_102/17...,https://search.pstatic.net/common/?type=b150&s...,500,500
97,여성 슬림핏 하이웨이스트 데님 청바지 봄 와이드 스트레이트 크롭 : 하유유통,https://shop-phinf.pstatic.net/20260605_15/178...,https://search.pstatic.net/common/?type=b150&s...,800,800
98,타미힐피거 기본 워싱 청바지 EMM3PD91A,http://shopping.phinf.naver.net/main_6623271/6...,https://search.pstatic.net/common/?type=b150&s...,500,500
99,TKX 남성 복고풍 자수 디테일 와이드 청바지 캐주얼 스타일 봄가을 워싱 편한 사진색,http://shopping.phinf.naver.net/main_5874184/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000

In [38]:
def get_image_list(query):
    'query로 검색한 이미지 정보(제목, 링크,썸네일, size) 100건 데이터 프레임을 return(방법2)'
    from dotenv import load_dotenv
    import os
    from urllib.request import urlopen, Request
    from urllib.parse import quote
    import json
    import pandas as pd
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    query = quote(query)
    url = f'https://openapi.naver.com/v1/search/image?query={query}&display=100'
    request = Request(url, headers=headers)
    response = urlopen(request)
    
    items = json.loads(response.read())['items']
    # print(items[:2])
    items_list = []
    for item in items:
        items_list.append({
            '제목':item.get('title'),
            '링크':item.get('link'),
            '썸네일':item.get('thumbnail'),
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
    return pd.DataFrame(items_list)
df = get_image_list("청바지")
df.sample()

,제목,링크,썸네일,sizeheight,sizewidth
73,여성용 청바지 탄성 부드러운 높은 허리 다리 TWE STR 넓은 코튼 포켓 블렌드 ...,http://shop1.phinf.naver.net/20260205_50/17702...,https://search.pstatic.net/common/?type=b150&s...,1000,1000

In [30]:
df.to_csv('data/img_list.csv', encoding='cp949', index=False)

In [31]:
# df에 있는 이미지 로컬에 저장하기
print(df.loc[1, '링크']) # 메인_01_청바지.jpg
print(df.loc[0, '썸네일']) # 썸네일_01_청바지.jpg

http://shopping.phinf.naver.net/main_5712970/57129708867.20251008173842.jpg
https://search.pstatic.net/sunny/?type=b150&src=https%3A%2F%2Fthumbnail.10x10.co.kr%2Fwebimage%2Fimage%2Fbasic600%2F741%2FB007415375.jpg%3Fcmd%3Dthumb%26w%3D500%26h%3D500%26fit%3Dtrue%26ws%3Dfalse

In [21]:
def save_image(attr, idx, link, query):
    'link의 이미지를 image/attr_idx_query.확장자로 local에 저장'
    import requests, os
    from urllib.parse import urlparse
    response = requests.get(link)
    content_type = response.headers.get('Content-Type')#확장자를 유추1
    print(content_type)
    file_extension = link.split('.')[-1]
    index = file_extension.find('?') # 확장자 뒤에 ?가 있는 위치(?가 없으면 -1)
    if index != -1:
        file_extension = file_extension[:index] # 물음표앞까지만 확장자로
    #허용할 이미지 확장자인지
    valid_extension = ['jpg','jpeg','png','gif','bmp','webp']
    if file_extension.lower() not in valid_extension:
        #허용할 이미지 확장자가 아닌경우(ex:.net)
        print(f'{idx}번째 {attr}의 url에서 확장자를 추출못하여 header에서 도전해봄')
        content_type = response.headers.get('Content-Type','') # image/jpeg
        file_extension = content_type.split('image/')[-1]# jpeg
        file_extension = file_extension.replace('jpeg','jpg')
        file_extension = file_extension if file_extension in valid_extension else 'jpg'
    #image 폴더가 없으면 image 폴더생성
    save_dir = 'image'
    os.makedirs(save_dir,exist_ok=True)
    #이미지 저장
    with open(f'{save_dir}/{attr}_{idx:02}_{query}.{file_extension}','wb')as f:
        f.write(response.content)#response의 바이너리를 저장
        
        
#     img = requests.get(link).content # link요청을 바이너리
#     with open(f'image/{attr}_{idx:02}_{query}.{file_extension}', 'wb') as f:
#         f.write(img) # 파일 저장
save_image('썸네일', 0, df.loc[0,'썸네일'], '청바지')

image/jpeg
0번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄

In [22]:
import pandas as pd
df = pd.read_csv('data/img_list.csv', encoding='cp949')

In [23]:
dff = df[df['링크'].str.find('?')==-1]
dff

,제목,링크,썸네일,sizeheight,sizewidth
1,여성용 와이드 하이웨스트 데님팬츠 데일리 청바지 5516,http://shopping.phinf.naver.net/main_5712970/5...,https://search.pstatic.net/common/?type=b150&s...,800,800
2,가을 겨울 일자핏 캐주얼 와이드 청바지 DNZK03 : 스마트 공장,http://shop1.phinf.naver.net/20241125_266/1732...,https://search.pstatic.net/common/?type=b150&s...,916,750
4,남자 와이드 스랙스 9부 바지 가 남성 청바지 루즈한 스트레이트 리 광저우 : so...,http://shop1.phinf.naver.net/20260331_151/1774...,https://search.pstatic.net/common/?type=b150&s...,1000,750
5,남자밴딩청바지 세미와이드청바지 통청바지 : 윤팬츠,http://shop1.phinf.naver.net/20250902_117/1756...,https://search.pstatic.net/common/?type=b150&s...,1000,1026
6,지앤제이 라이크 슬림 일자진 여자청바지 청바지,https://cdn2.halfclub.com/cdn/product/A7548/P3...,https://search.pstatic.net/sunny/?type=b150&sr...,640,640
...,...,...,...,...,...
95,MOSAIRATION 여성 청바지 하이웨스트 캐주얼 스트레이트 데님 팬츠 M0011214,http://shopping.phinf.naver.net/main_5905233/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000
96,여성 바지 빈티지 캐주얼 가을 청바지 데님바지 엘보 배기핏 와이드 워싱 데일룩 DA...,https://shop-phinf.pstatic.net/20260225_102/17...,https://search.pstatic.net/common/?type=b150&s...,500,500
97,여성 슬림핏 하이웨이스트 데님 청바지 봄 와이드 스트레이트 크롭 : 하유유통,https://shop-phinf.pstatic.net/20260605_15/178...,https://search.pstatic.net/common/?type=b150&s...,800,800
98,타미힐피거 기본 워싱 청바지 EMM3PD91A,http://shopping.phinf.naver.net/main_6623271/6...,https://search.pstatic.net/common/?type=b150&s...,500,500
99,TKX 남성 복고풍 자수 디테일 와이드 청바지 캐주얼 스타일 봄가을 워싱 편한 사진색,http://shopping.phinf.naver.net/main_5874184/5...,https://search.pstatic.net/common/?type=b150&s...,1000,1000

In [24]:
#naver api 요청받아 이미지제목,link,썸네일link 정보를 csv로 백업, 이미지link와 썸네일 link 이미지를 다운

In [34]:
def get_image_list_save_file(query):
    '''
    naver api 요청받아 이미지제목,link,섬네일link 정보를 데이터 프래임으로 return
    데이터 프래임을 csv로 백업
    d이미지link와 썸네일 link 이미지를 다운(방법2)
    '''     
    'query로 검색한 이미지 정보(제목, 링크,썸네일, size) 100건 데이터 프레임을 return(방법2)'
    from dotenv import load_dotenv
    import os
    from urllib.request import urlopen, Request
    from urllib.parse import quote
    import json
    import pandas as pd
    load_dotenv()
    client_id = os.getenv('CLIENT_ID')
    client_secret = os.getenv('CLIENT_SECRET')
    headers = {
        'X-Naver-Client-Id': client_id,
        'X-Naver-Client-Secret':client_secret
    }
    query = quote(query)
    url = f'https://openapi.naver.com/v1/search/image?query={query}&display=100'
    request = Request(url, headers=headers)
    response = urlopen(request)
    
    items = json.loads(response.read())['items']
    items_list = []
    for idx, item in enumerate(items):
        link = item.get('link')
        thumbnail = item.get('thumbnail')
        items_list.append({
            '제목':item.get('title'),
            '링크':link,
            '썸네일':thumbnail,
            'sizeheight':item.get('sizeheight'),
            'sizewidth':item.get('sizewidth')
        })
        #이미지 저장 save_image('매인', idx, link, query') save_image('썸네일', idx, thimnail,query)
        save_image('매인',idx,link,query)
        save_image('썸네일',idx,link,query)
        if idx%20==0:
            print(f'==={idx}%진행완료===')
    result = pd.DataFrame(items_list)
    result.to_csv('image/img_list.csv',index=False)
    print('이미지 및 csv저장완료')
    return result

In [36]:
df=get_image_list_save_file("김혜수")

image/jpeg
image/jpeg
===0%진행완료===
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/png
image/png
image/png
image/png
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
12번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
12번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/webp
image/webp
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
text/html
17번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
text/html
17번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
image/jpeg
text/html
19번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
text/html
19번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
image/jpeg
===20%진행완료===
image/jpeg
21번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
21번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/webp
image/webp
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
28번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
28번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/webp
image/webp
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/png
image/png
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/png
image/png
===40%진행완료===
image/jpeg
image/jpeg
image/png
image/png
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/png
image/png
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg;charset=UTF-8
image/jpeg;charset=UTF-8
image/jpeg
image/jpeg
text/html
52번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
text/html
52번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/png
image/png
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
===60%진행완료===
image/webp
image/webp
image/jpeg
image/jpeg
image/png
image/png
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/gif
image/gif
image/webp
image/webp
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
text/html; charset=UTF-8
text/html; charset=UTF-8
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg;charset=UTF-8
image/jpeg;charset=UTF-8
===80%진행완료===
image/jpeg
image/jpeg
image/jpeg
image/jpeg
text/html; charset=UTF-8
text/html; charset=UTF-8
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
87번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
87번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
94번째 매인의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
94번째 썸네일의 url에서 확장자를 추출못하여 header에서 도전해봄
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
이미지 및 csv저장완료

## 2.3 XML웹 데이터 수집
- RSS서비스,openAPI사용

### 1)전국 날씨 RSS를 BeautifulSoup을 이용한 xml크롤링
- 기상청 RSS에서 1개월 기상정보를 서비스

In [48]:
import requests
#from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
items_list = []
url = 'https://www.kma.go.kr/repositary/xml/fct/mon/img/fct_mon1rss_108_20260813.xml'
target = requests.get(url)
soup = BeautifulSoup(target.text,'xml')
locals = soup.select('local_ta')
print(locals[1])
for local in locals:
    local_name = local.select_one('local_ta_name').text.strip()
    week1_local_ta_normalYear=local.select_one('week1_local_ta_normalYear').text #평년기온
    week1_local_ta_similarRange=local.select_one('week1_local_ta_similarRange').text #예측범위
    week1_local_ta_minVa       =local.select_one('week1_local_ta_minVa ').text #평년보다 낮을 확률
    week1_local_ta_similarVa   =local.select_one('week1_local_ta_similarVa').text #평년과 비슷할 확률
    week1_local_ta_maxVal      =local.select_one('week1_local_ta_maxVal').text #평년보다 높을 확률
    items_list.append({
        '지역':local_name,
        '평년기온':week1_local_ta_normalYear,
        '예측범위':week1_local_ta_similarRange,
        '낮을확률':week1_local_ta_minVa,
        '같을확률':week1_local_ta_similarVa,
        '높을확률':week1_local_ta_maxVal ,        
    })
df = pd.DataFrame(items_list)
df.head()

<local_ta>
<local_ta_name> 서울ㆍ인천ㆍ경기도 </local_ta_name>
<week_local_ta>
<week1_local_ta_normalYear>23.9</week1_local_ta_normalYear>
<week1_local_ta_similarRange>23.3~24.5</week1_local_ta_similarRange>
<week1_local_ta_minVal>10</week1_local_ta_minVal>
<week1_local_ta_similarVal>30</week1_local_ta_similarVal>
<week1_local_ta_maxVal>60</week1_local_ta_maxVal>
</week_local_ta>
<week_local_ta>
<week2_local_ta_normalYear>23.1</week2_local_ta_normalYear>
<week2_local_ta_similarRange>22.6~23.6</week2_local_ta_similarRange>
<week2_local_ta_minVal>20</week2_local_ta_minVal>
<week2_local_ta_similarVal>30</week2_local_ta_similarVal>
<week2_local_ta_maxVal>50</week2_local_ta_maxVal>
</week_local_ta>
<week_local_ta>
<week3_local_ta_normalYear>21.7</week3_local_ta_normalYear>
<week3_local_ta_similarRange>21.1~22.3</week3_local_ta_similarRange>
<week3_local_ta_minVal>20</week3_local_ta_minVal>
<week3_local_ta_similarVal>30</week3_local_ta_similarVal>
<week3_local_ta_maxVal>50</week3_local_ta_maxVal>
</week_local_ta>
<week_local_ta>
<week4_local_ta_normalYear>20.8</week4_local_ta_normalYear>
<week4_local_ta_similarRange>20.2~21.4</week4_local_ta_similarRange>
<week4_local_ta_minVal>10</week4_local_ta_minVal>
<week4_local_ta_similarVal>40</week4_local_ta_similarVal>
<week4_local_ta_maxVal>50</week4_local_ta_maxVal>
</week_local_ta>
</local_ta>

AttributeError: 'NoneType' object has no attribute 'text'

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   제목          100 non-null    object
 1   링크          100 non-null    object
 2   썸네일         100 non-null    object
 3   sizeheight  100 non-null    object
 4   sizewidth   100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB

In [ ]:
df['평년기온']=df['평년기온'].astype(np.float64)
df['낮을확률']=df['낮을확률'].astype(np.int16)
df['평년기온']=df['평년기온'].astype(np.float64)
df['평년기온']=df['평년기온'].astype(np.float64)

### 2)xml로 응답하는 openAPI 활용
- data.go.kr에서
    * 서울특별시_노선정보조회 서비스(버스 id,버스정류장 목록-정류장id와 정류장이름)
    * 서울특별시_버스위치정보조회 서비스(실시간 버스 위치 목록)

In [ ]:
# step 1 : 버스번호의 id받아오기
# 서울특별시_노선정보조회 서비스 : 노선번호 목록조회(3번.getBusRouteList)
# http://api.bus.go.kr/contents/sub02/GetBusPosByRtid.html

In [34]:
# 인증키
from dotenv import load_dotenv
import os
load_dotenv()
serviceKey = os.getenv('Key')

In [35]:
import requests
from urllib.request import quote
from bs4 import BeautifulSoup
from urllib.request import urlretrieve # xml을 로컬에 저장
busNum = '506'
key = os.getenv('Key')
url1 = f'http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey={key}&strSrch={busNum}'
print(url1)
#요청받은 xml을 로컬에 백업
# savefilename1 = 'data/ch14_1.busInfo.xml'
# urlretrieve(url1,savefilename1)
# with open(savefilename1,encoding='utf-8')as f:
#     xml=f.read();
# soup = BeautifulSoup(xml,'xml')
xml = requests.get(url1)
soup = BeautifulSoup(xml.text,'xml')

http://ws.bus.go.kr/api/rest/busRouteInfo/getBusRouteList?ServiceKey=3032418fd9a55474722f4098cf3e6dfb52c52ad77fee2e14386389a9b36c7b0a&strSrch=506

In [36]:
soup.select('itemList')

[<itemList><busRouteAbrv>506</busRouteAbrv><busRouteId>100100081</busRouteId><busRouteNm>506</busRouteNm><corpNm>한남여객  02-873-8730</corpNm><edStationNm>을지로입구역.광교</edStationNm><firstBusTm>20260814042000</firstBusTm><firstLowTm>20210420000000</firstLowTm><lastBusTm>20260814222000</lastBusTm><lastBusYn> </lastBusYn><lastLowTm>20210420000000</lastLowTm><length>44.104</length><routeType>3</routeType><stStationNm>신림2동차고지</stStationNm><term>15</term></itemList>]

In [37]:
for item in soup.select('itemList'):
    busRouteAbrv = item.select_one('busRouteAbrv').text
    if busNum == busRouteAbrv:
        busRouteId = item.find('busRouteId').text
        break
print('busRouteId-=',busRouteId)

busRouteId-= 100100081

step 2. 해당 busRouteId의 정류장 목록 받아오기(정류장id,정류장이름)
    서울특별시_노선정보조회 서비스 -4번 기능(getStationByR

In [41]:
import pandas as pd
url2 = f'http://ws.bus.go.kr/api/rest/busRouteInfo/getStaionByRoute?ServiceKey={key}&busRouteId={busRouteId}'
print(url2)
response=requests.get(url2)
soup = BeautifulSoup(response.text,'xml')
itemList = soup.select('itemList')
print(f'{busNum}번 정류장 갯수:',len(itemList))
bus_station = []
for itemList in itemList:
    stationNm = itemList.select_one('stationNm').text
    station   = itemList.select_one('station').text
    gpsX      = itemList.select_one('gpsX').text
    gpsY      = itemList.select_one('gpsY').text
    bus_station.append([stationNm,station,gpsX,gpsY])
df_station = pd.DataFrame(bus_station,columns=['정류소명','id','경도','위도'])
df_station

http://ws.bus.go.kr/api/rest/busRouteInfo/getStaionByRoute?ServiceKey=3032418fd9a55474722f4098cf3e6dfb52c52ad77fee2e14386389a9b36c7b0a&busRouteId=100100081
506번 정류장 갯수: 100

                 정류소명         id              경도             위도
0   신림중.삼성고.관악아트홀·도서관  120000041      126.944412      37.470352
1        서울산업정보학교.삼성교  120000042   126.941124806  37.4710142867
2              신성초등학교  120000043      126.937427      37.471078
3             삼성동주민센터  120000063      126.933025      37.470005
4                미림고개  120000064      126.931983      37.468114
..                ...        ...             ...            ...
95           서울대벤처타운역  120000078      126.933592      37.470692
96           대학동고시촌입구  120000056      126.938381      37.470538
97       서울산업정보학교.삼성교  120000057  126.9420276971   37.470573816
98  관악산입구.관악아트홀·중앙도서관  120000058      126.946871      37.467758
99              서울대학교  120000028  126.9479522861  37.4667414611

[100 rows x 4 columns]

In [ ]:
# step 3 : 해당 busRouteId의 차량들의 위치정보 (차량번호,혼잡도,경도,위도,최종정류장id,다음정류장id,도착소요시간)
# 서울특별시_버스위치 정보조회 서비스 : 2번 가능(getBusPosByRtidList)
# http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid

In [51]:
url3=f'http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?serviceKey={key}&busRouteId={busRouteId}'
print(url3)
response = requests.get(url3)
soup = BeautifulSoup(response.text,'xml')
itemLists = soup.select('itemList')
print(f'{busNum}번 운행중인 버스는{len(itemList)}대입니다.')
bus_station = [] #버스 정보위치를 담을 list
for itemList in itemLists:
    plainNo = itemList.select_one('plainNo').text #차량번호
    congetion = itemList.select_one('congetion').text 
    # 혼잡도(0 : 없음, 3 : 여유, 4 : 보통, 5 : 혼잡)
    congetion ='없음' if congetion=='0' \
            else'여유' if congetion=='3' \
            else'보통' if congetion=='4' \
            else'혼잡' 
    gpsX = itemList.select_one('gpsX').text #경도
    gpsY = itemList.select_one('gpsY').text #위도
    lastStnId = itemList.select_one('lastStnId').text #최종정류소id
    nextStId  = itemList.select_one('nextStId').text #다음정류소id
    nextStTm  = itemList.select_one('nextStTm').text #다음정류소도착소요시간
    bus_station.append({
        '차량번호':plainNo,
        '혼잡도':congetion,
        '경도':gpsX,
        '위도':gpsY,
        '최종정류소id':lastStnId,
        '다음정류소id':nextStId,
        '도착소요시간':nextStTm
    })
df_position = pd.DataFrame(bus_station)
df_position.head()

http://ws.bus.go.kr/api/rest/buspos/getBusPosByRtid?serviceKey=3032418fd9a55474722f4098cf3e6dfb52c52ad77fee2e14386389a9b36c7b0a&busRouteId=100100081
506번 운행중인 버스는23대입니다.

        차량번호 혼잡도          경도         위도    최종정류소id    다음정류소id 도착소요시간
0  서울75사1335  여유  126.935543  37.471288  120000043  120000018   1902
1  서울75사1316  여유  126.919066  37.461113  120000166  120000018   1091
2  서울74사3713  보통  126.925221  37.483607  120000017  120000018    160
3  서울70사8996  여유  126.945365  37.481936  120000020  119000073    879
4  서울70사8994  여유  126.956582  37.492672  119000075  119000073    147

In [57]:
df_station.loc[df_station['id']=='119000075','정류소명'].iloc[0]

'봉천고개.관악현대아파트'

In [63]:
def get_station_name(row):
    row['최종정류소명'] = df_station.loc[df_station['id']==row['최종정류소id'],'정류소명'].iloc[0]
    row['다음정류소명'] = df_station.loc[df_station['id']==row['다음정류소id'],'정류소명'].iloc[0]
    return row

In [67]:
# get_station_name(df_position.iloc[0])
df_position.apply(get_station_name,axis=1)
df_position.head(2)

        차량번호 혼잡도          경도         위도    최종정류소id    다음정류소id 도착소요시간
0  서울75사1335  여유  126.935543  37.471288  120000043  120000018   1902
1  서울75사1316  여유  126.919066  37.461113  120000166  120000018   1091

In [70]:
drop_col = df_position.columns.str.contains('id')
drop_column_names = df_position.columns[drop_col]
df_position.drop(drop_column_names,axis=1, inplace=True)

In [72]:
df_position['도착소요시간']=round(df_position['도착소요시간'].astype('int')/60,2)
df_position.head()

        차량번호 혼잡도          경도         위도  도착소요시간
0  서울75사1335  여유  126.935543  37.471288   31.70
1  서울75사1316  여유  126.919066  37.461113   18.18
2  서울74사3713  보통  126.925221  37.483607    2.67
3  서울70사8996  여유  126.945365  37.481936   14.65
4  서울70사8994  여유  126.956582  37.492672    2.45

# 3절. 연습문제
- YES24 베스트셀러 정보에서 순위1~48위까지의 "순위, 책이름, 저자, 출판사, 가격 정보를 출력하고 ch14_yes24_bestseller.csv로 백업

In [73]:
from requests import get
from bs4 import BeautifulSoup
import pandas import get
pages = 2
items_list = []
header = {'user-agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'
    }
for page in range(1,pages+1):
    url = f'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber={page}&pageSize=24'
    response = get(url,headers=headers) 
    soup = BeautifulSoup(response.text,'html.parser')
    books = soup.find_all('li',attrs={'data-goods-no':True})
         
    for book in books: 
        title_els = book.select_one('.gd_name')
        author_els = book.select_one('.info_auth')
        publisher_els = book.select_one('.info_pub')
        price_els = book.select_one('yes_b')
        
        if title:                  
            items_list.append({
                '책이름':title_els.text.strip(),
                '저자':author_els.text.strip()
                if author_els else '',
                '출판사':
            })
df = pd.DataFrame(items_list)

SyntaxError: invalid syntax (1364665795.py, line 3)

In [ ]:
dt_els = soup.find_all('a', 'gd_name')
title_els = soup.find_all('a',class_='gd_name')