In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

<font color="red" size="6">ch14. 웹데이터 수집</font>
<!-- # <span style="color:red">ch14. 웹데이터 수집</span> -->
# 1절. BeautifulSoup과 parser
    (정적 웹크롤링, 공공api사용)
    
`pip install bs4` 아나콘다를 설치하면 자동 설치되는 패키지에 포함
- 공식사이트 : https://www.crummy.com/software/BeautifulSoup/
- documentation : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [16]:
import requests #HTTP 요청 처리하는 lib
#file:// ==c:
#http://www.
from requests_file import FileAdapter

In [17]:
# 로컬에 있는 파일을 웹요청하듯이 읽어오는 작업
s = requests.Session()
s.mount("file://",FileAdapter()) #file://로 시작하는 url을 어뎁터가 처리
response = s.get("file:///ai/source/01_python/data/ch14_sample.html")# c:/ai/lecNote/data/ch14_sample.html
response

In [18]:
%ls "C:\ai\source\01_python\data"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 0C81-36F7

 C:\ai\source\01_python\data 디렉터리

2026-07-24  오전 11:45    <DIR>          .
2026-08-12  오전 11:10    <DIR>          ..
2026-07-23  오후 07:25    <DIR>          .ipynb_checkpoints
2026-07-21  오전 09:29           221,370 0722_예제1_아파트분양가분석.docx
2026-07-07  오후 04:52                32 ch08.txt
2026-07-08  오후 06:36                84 ch09.txt
2026-07-09  오후 05:53               210 ch09_customers.txt
2026-07-09  오후 02:35         1,069,192 ch09_iris.h5
2026-07-08  오후 05:59               281 ch09_member.pkl
2025-04-21  오후 09:06               161 ch09_member.txt
2024-11-18  오후 02:56               170 ch09_member1.csv
2026-07-09  오후 12:48               327 ch09_member1.json
2024-11-18  오후 04:51               131 ch09_member1-cp.csv
2026-07-09  오후 12:47               273 ch09_member2.json
2026-07-09  오전 10:50               128 ch09_member2-write-cp.csv
2024-11-18  오후 04:27               159 ch09_member3.csv
2026-07-09  오전 11:44               180 ch09_member4.csv
2026-07-10  오후 12:44               209 ch10.pkl
2026-07-10  오후 12:47               188 ch11.npy
2026-07-15  오후 12:39             4,009 ch11_iris.csv
2026-07-15  오후 12:39               976 ch11_iris.zip
2025-04-28  오후 04:53               361 ch11_member.csv
2024-11-25  오후 03:22               312 ch11_membercp949.csv
2024-11-25  오후 03:19               361 ch11_membersep.csv
2024-11-25  오후 03:21               361 ch11_membertab.csv
2026-07-24  오후 06:34            63,357 ch12_plot.png
2026-07-23  오후 07:25           848,656 ch13_연습포트폴리오_아파트분양가분석.ipynb
2026-07-23  오전 10:52           690,589 ch13_예1_포트폴리오_아파트분양가분석_원본.ipynb
2025-11-09  오후 06:59               528 ch14_sample.html
2026-07-23  오후 06:00            59,709 df(최종).csv
2026-07-24  오전 09:35           394,458 df_last.csv
2026-07-08  오후 06:39               126 ex.txt
2026-07-08  오후 06:42               163 exex.txt
2026-07-07  오후 04:52                39 test.txt
2026-06-24  오후 10:04             2,163 전국 평균 평당 분양가격(2013년 9월부터 2015년 8월까지).csv
2026-07-14  오후 05:35           501,367 주택도시보증공사_전국 신규 민간아파트 분양가격 동향_20260531.csv
              33개 파일           3,860,630 바이트
               3개 디렉터리  117,123,813,376 바이트 남음

In [19]:
if response:
    print('해당 url에 접근함')
else:
    print('해당 url에 거부됨')

해당 url에 접근함

In [20]:
response.status_code
#200 : 정상
#404 : 없는 패이지

200

In [21]:
response.content #html의 바이너리 형식

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [22]:
print(response.content.decode('utf-8'))

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [23]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [24]:
#html 파싱 객체
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text,#response.content,
                    "html.parser")
# soup

In [31]:
#soup.select_one('선택자') : 해당 선택자 처음 하나 엘리먼트만
el = soup.select_one('h1.greeting.css')
print('el=',el)
print('el.text=>',el.text)
print('el.string=>',el.string)
print('el의 속성들=>',el.attrs)
print('el의 class속성=>',el.attrs['class'])
print('el의 class속성=>',el.attrs.get('class'))
#print('el의 href속성(없는 속성은 에러)=>',el.attrs.get['href'])
print('el의 href속성(없는 속성은 에러)=>',el.attrs.get('href'))

el= <h1 class="greeting css" id="text">Hello, CSS</h1>
el.text=> Hello, CSS
el.string=> Hello, CSS
el의 속성들=> {'class': ['greeting', 'css'], 'id': 'text'}
el의 class속성=> ['greeting', 'css']
el의 class속성=> ['greeting', 'css']

In [35]:
# 2. soup.select('선택자') : 해당 선택자 엘리먼트 다 배열로
els=soup.select('h1.css')
print('el=>',els)
print('els들의 text',[el.text for el in els])
print('els들의 string',[el.string for el in els])
print('els들의 속성들',[el.attrs for el in els])
print('els들의 class 속성',[el.attrs.get('class') for el in els])

el=> [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els들의 text ['Hello, CSS', 'Hi, CSS']
els들의 string ['Hello, CSS', 'Hi, CSS']
els들의 속성들 [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els들의 class 속성 [['greeting', 'css'], ['css']]

In [39]:
# 3.soup.find(태그,속성) vs soup.select_one('선택자'):해당 속성을 가진 태그 처음 하나만
print('select_one:',soup.select_one('h1.css'))
print('find      :',soup.find('h1',{'class':'css'}))
print('find      :',soup.find('h1',class_='css'))
print()
print('select_one:',soup.select_one('h1#text'))
print('select_one:',soup.find('h1',{'id':'text'}))

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>
find      : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>
select_one: <h1 class="greeting css" id="text">Hello, CSS</h1>

In [42]:
# 4.soup.find_all(태그,속성) vs soup.select_one('선택자'):해당 엘리먼트 다 list로
print('모든 h1.css.greeting와 span태그:',soup.select('h1.css.greeting,span'))
print('모든 h1.css.greeting와 span태그:',soup.find_all(['h1'],class_='css')+
                                        soup.find_all('span'))

모든 h1.css.greeting와 span태그: [<h1 class="greeting css" id="text">Hello, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css.greeting와 span태그: [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]

In [45]:
# 없는 엘리먼트 찾기
print('find_all(빈list):',soup.find_all('a'))
print('find(None)     :',soup.find('a'))
print('select(빈list):',soup.select('a'))
print('select_one(None):',soup.select_one('a'))

find_all(빈list): []
find(None)     : None
select(빈list): []
select_one(None): None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
## 2.1BeautifulSoup 모듈을 활용한 html웹 데이터 수집
### 1)환율정보 가져오기(네이버 증권>시장지표)

-https://finance.naver.com/marketindex/

    * 크롤링 허용범위는 사이트 마다~/robots.txt에서 확인할수있음
        -Allow : 크롤링 허용가능한 폴더
        -Disallow : 크롤링 제한 폴더

In [77]:
# soup객체 생성 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex/'
response = requests.get(url)
response #Response
print(response.status_code)
# print(response.text)#response.content
soup = BeautifulSoup(response.text,'html.parser')

200

In [78]:
# soup객체 생성 방법2
from urllib.request import urlopen
url = 'https://finance.naver.com/marketindex/'
response = urlopen(url)
#response # HTTPResponse
print(response.status)
#print(response.read().decode('cp949'))
soup = BeautifulSoup(response,'html.parser')

200

In [79]:
p='1,417.70'
float(p.replace(',',''))#방법1
float(''.join(p.split(',')))#방법2

1417.7

In [80]:
# div.head_info 밑의 span.value(find계열)
prices=[]
headinfos = soup.find_all('div',class_='head_info')
for headinfo in headinfos:
    #print(headinfo)
    price = headinfo.find('span',class_='value')
    prices.append(float(''.join(price.text.split(','))))
print(prices)

[1414.7, 887.43, 1631.57, 209.66, 159.24, 1.1541, 1.3507, 99.71, 83.2, 1863.86, 4441.1, 199900.3]

In [81]:
# span.value(find 계열)
price_els = soup.find_all('span',class_='value')
prices = [float(price.text.replace(',',''))for price in price_els]
print(prices)

[1414.7, 887.43, 1631.57, 209.66, 159.24, 1.1541, 1.3507, 99.71, 83.2, 1863.86, 4441.1, 199900.3]

In [82]:
# 금액들 div.head_info 밑의 span.value
price_els = soup.select('div.head_info>span.value')
#price_els

In [83]:
#타이틀
title_els = soup.select('h3.h_lst>span.blind')
title_els

[<span class="blind">미국 USD</span>,
 <span class="blind">일본 JPY(100엔)</span>,
 <span class="blind">유럽연합 EUR</span>,
 <span class="blind">중국 CNY</span>,
 <span class="blind">달러/일본 엔</span>,
 <span class="blind">유로/달러</span>,
 <span class="blind">영국 파운드/달러</span>,
 <span class="blind">달러인덱스</span>,
 <span class="blind">WTI</span>,
 <span class="blind">휘발유</span>,
 <span class="blind">국제 금</span>,
 <span class="blind">국내 금</span>]

In [88]:
#단위들 : div.head_info span blind
unit_els = soup.select('div.head_info>span>span.blind')
len(unit_els)
units=[unit_el.string for unit_el in unit_els]
units.insert(7,'')
units

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [90]:
trend_els = soup.select('div.head_info>span.blind')

In [91]:
for title,price,unit,trend in zip(title_els, price_els, units,trend_els):
    print("{}:{} {}-{}".format(title.text,price.text,unit,trend.text))

미국 USD:1,414.70 원-상승
일본 JPY(100엔):887.43 원-상승
유럽연합 EUR:1,631.57 원-상승
중국 CNY:209.66 원-상승
달러/일본 엔:159.2400 엔-상승
유로/달러:1.1541 달러-하락
영국 파운드/달러:1.3507 달러-하락
달러인덱스:99.7100 -상승
WTI:83.2 달러-상승
휘발유:1863.86 원-하락
국제 금:4441.1 달러-상승
국내 금:199900.3 원-상승

In [96]:
import pandas as pd
data = []
for title,price,unit,trend in zip(title_els, price_els, units,trend_els):
    data.append({'title':title.text,
                 'price':float(price.text.replace(',','')),
                 'unit' :unit,
                 'trend':trend.text})
                               
pd.DataFrame(data)#.to_csv('data/file.csv',index=False)

           title        price unit trend
0         미국 USD    1414.7000    원    상승
1   일본 JPY(100엔)     887.4300    원    상승
2       유럽연합 EUR    1631.5700    원    상승
3         중국 CNY     209.6600    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.8600    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  199900.3000    원    상승

In [97]:
data = []
for title,price,unit,trend in zip(title_els, price_els, units,trend_els):
    data.append([title.text,float(price.text.replace(',','')),unit,trend.text])
pd.DataFrame(data,columns=['title','price','unit','trend'])

           title        price unit trend
0         미국 USD    1414.7000    원    상승
1   일본 JPY(100엔)     887.4300    원    상승
2       유럽연합 EUR    1631.5700    원    상승
3         중국 CNY     209.6600    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.8600    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  199900.3000    원    상승

### 2)이번주 로또번호 출력
- 방법2에서 UserAgent를 추가하여 soup생성
- https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto(다음에서 lotto검색)
```
    1236회(2026.08.08 추첨)
    당첨번호 [12,18,21,29,34,38]
    보너스 10
```

In [105]:
# 방법1
import requests
from bs4 import BeautifulSoup
url ='https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
response = requests.get(url)
print('response의 상태:',response.status_code)
soup = BeautifulSoup(response.text,'html.parser')
#soup

response의 상태: 200

In [117]:
# 방법2
from urllib.request import urlopen, Request
headers = {'User-Agent':
           'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}       
request =Request(url,headers=headers)

response =urlopen(request)
print('response의 상태:',response.status)
soup = BeautifulSoup(response,'html.parser')
#soup

response의 상태: 200

In [109]:
#1236회(2026.08.08 추첨)
# 당첨번호 [12, 18, 21, 29, 34, 38]
# 보너스 10
times = soup.select_one('div.prize  span.f_red').text
date = soup.select_one('div.prize > span.date').text
title1 = soup.select_one('div.prize > strong').text[-4:]
lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
title2 = soup.select_one('div.lottonum span.screen_out').text
bonus_number = soup.select_one('div.lottonum > span.bg_ball1').text
print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

In [118]:
# 위의 select계열 함수를 find계열함수로 변경하여 구현해보기
#times = soup.select_one('div.prize  span.f_red').text
prize = soup.find('div',class_='prize')
times = prize.find('span',class_='f_red').text
#date = soup.select_one('div.prize > span.date').text
date = prize.find('span', class_='date').text
#title1 = soup.select_one('div.prize > strong').text[-4:]
title1 = prize.find('strong').text[-4:]
#lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
lottonum = soup.find('div', class_='lottonum')
#lotto_numbers = soup.select('div.lottonum > span.ball')[:-2]
lotto_numbers = lottonum.find_all('span', class_='ball')[:-2]

#title2 = soup.select_one('div.lottonum span.screen_out').text
title2 = lottonum.find('span', class_='screen_out').text

#bonus_number = soup.select_one('div.lottonum > span.bg_ball1').text
bonus_number = lottonum.find('span', class_='bg_ball1').text
print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2,bonus_number)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

### 3)다음 뉴스 검색 리스트
```
no title  href
0 타이틀1  http://~
1 타이틀2  http://~ 
2 타이틀3  http://~
```

In [120]:
# 방법1
import requests
from bs4 import BeautifulSoup
word = '비트코인'
url = f'https://search.daum.net/search?w=news&q={word}'
print(url)
response = requests.get(url)
print(response.status_code)
soup = BeautifulSoup(response.text,'html.parser')

https://search.daum.net/search?w=news&q=비트코인
200

In [125]:
#방법2
from urllib.request import urlopen,Request
from urllib.parse import quote
word = quote('비트코인')
url = f'https://search.daum.net/search?w=news&q={word}'
headers = {'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request = Request(url)
request.add_header('User-Agent',
                  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
response = urlopen(request)
print(response.status)
soup = BeautifulSoup(response,'html.parser')
#soup

200

In [130]:
items_find_list = []
items_el = soup.select('div.item-title>strong.tit-g >a')
for idx, item in enumerate(items_el):
    #print(idx,item.attrs['href'])
    items_find_list.append({'no':idx,
                            'title':item.text,
                            'link':item.attrs.get('href')})
import pandas as pd
pd.DataFrame(items_find_list)

,no,title,link
0,0,9000만원 깨진 비트코인…美물가지수 앞두고 위험회피 심리↑,http://v.daum.net/v/20260812104759348
1,1,9000만원대 갇힌 비트코인…'100만弗 vs 4만弗' 극단 전망,http://v.daum.net/v/20260812161211645
2,2,[코인뉴스] CPI 앞둔 비트코인…박스권 속 엇갈린 베팅,http://v.daum.net/v/20260812163039451
3,3,비트코인 다시 6.3만달러대로…美 CPI 발표 ‘촉각’ [코인 모닝콜],http://v.daum.net/v/20260812082137419
4,4,[코인뉴스] 비트코인 박스권 지속…다음 변수는?,http://v.daum.net/v/20260812093050056
5,5,[코인시세] 비트코인 6만3천달러대 약세…CPI 경계감 지속,http://v.daum.net/v/20260812103841887
6,6,"[08:03 가상자산] 비트코인, 美 CPI 결과 발표 앞두고 9000만원 선 붕괴",http://v.daum.net/v/20260812080815138
7,7,[아주경제 코이너스 브리핑] 호르무즈 불확실성에…비트코인 6만3000달러대 횡보,http://v.daum.net/v/20260812082712570
8,8,"트럼프 회사, 비트코인에 3300억 베팅했다 '쓴맛'⋯손실 12배 늘었다",http://v.daum.net/v/20260811144238992
9,9,"금리 공포 걷히자 ""금값 조정 끝났다""… 비트코인은 나 홀로 약세",http://v.daum.net/v/20260812164709172

In [131]:
items_find_list = []
items_el = soup.select('div.item-title>strong.tit-g >a')
for idx,item in enumerate(items_el):
    items_find_list.append([idx,item.text,item.attrs.get('href')])
pd.DataFrame(items_find_list,columns=['순번','기사제목','링크'])

,순번,기사제목,링크
0,0,9000만원 깨진 비트코인…美물가지수 앞두고 위험회피 심리↑,http://v.daum.net/v/20260812104759348
1,1,9000만원대 갇힌 비트코인…'100만弗 vs 4만弗' 극단 전망,http://v.daum.net/v/20260812161211645
2,2,[코인뉴스] CPI 앞둔 비트코인…박스권 속 엇갈린 베팅,http://v.daum.net/v/20260812163039451
3,3,비트코인 다시 6.3만달러대로…美 CPI 발표 ‘촉각’ [코인 모닝콜],http://v.daum.net/v/20260812082137419
4,4,[코인뉴스] 비트코인 박스권 지속…다음 변수는?,http://v.daum.net/v/20260812093050056
5,5,[코인시세] 비트코인 6만3천달러대 약세…CPI 경계감 지속,http://v.daum.net/v/20260812103841887
6,6,"[08:03 가상자산] 비트코인, 美 CPI 결과 발표 앞두고 9000만원 선 붕괴",http://v.daum.net/v/20260812080815138
7,7,[아주경제 코이너스 브리핑] 호르무즈 불확실성에…비트코인 6만3000달러대 횡보,http://v.daum.net/v/20260812082712570
8,8,"트럼프 회사, 비트코인에 3300억 베팅했다 '쓴맛'⋯손실 12배 늘었다",http://v.daum.net/v/20260811144238992
9,9,"금리 공포 걷히자 ""금값 조정 끝났다""… 비트코인은 나 홀로 약세",http://v.daum.net/v/20260812164709172

In [134]:
# 다음 뉴스 검색 함수(원하는 키워드, 원하는 패이지로)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
def collect_list(keyword,page):
    'keyword로 해당 page에 검색한 결과 return'
    #url = f'https://search.daum.net/search?w=news&q={keyword}&p={page}'
    url = 'https://search.daum.net/search?w=news'
    params = {'q':keyword,'p':page}
    response = request.get(url,params=params)
    soup = BeautifulSoup(response.text,'html.parser')
    items_find_list = []
    items_el = soup.select('div.item-title>strong.tit-g >a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10 + idx,
                                'title':item.text,
                                'link': item.attrs.get('href')})
    return items_find_list

In [138]:

collect_list('배이스볼',2)

AttributeError: 'Request' object has no attribute 'get'