In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

In [3]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head()
iris.iloc[::50]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [4]:
# 1. sepal_length 열만 출력
iris['sepal_length']
iris.sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [5]:
# 2. 0~10행까지 마지막 열을 제외한 데이터 (loc, iloc)
iris.loc[:10,'sepal_length':'petal_width']

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
5            5.4          3.9           1.7          0.4
6            4.6          3.4           1.4          0.3
7            5.0          3.4           1.5          0.2
8            4.4          2.9           1.4          0.2
9            4.9          3.1           1.5          0.1
10           5.4          3.7           1.5          0.2

In [6]:
iris.iloc[:11,:-1]

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
5            5.4          3.9           1.7          0.4
6            4.6          3.4           1.4          0.3
7            5.0          3.4           1.5          0.2
8            4.4          2.9           1.4          0.2
9            4.9          3.1           1.5          0.1
10           5.4          3.7           1.5          0.2

In [7]:
# 3. 3~10 행중에 'sepal_length'와 'petal_length' 열만 (loc, iloc)
iris.loc[3:10,['sepal_length','petal_length']]

    sepal_length  petal_length
3            4.6           1.5
4            5.0           1.4
5            5.4           1.7
6            4.6           1.4
7            5.0           1.5
8            4.4           1.4
9            4.9           1.5
10           5.4           1.5

In [8]:
iris.iloc[3:10,[0,2]]

   sepal_length  petal_length
3           4.6           1.5
4           5.0           1.4
5           5.4           1.7
6           4.6           1.4
7           5.0           1.5
8           4.4           1.4
9           4.9           1.5

In [9]:
# 4. 0번째, 50번째, 100번째 행의 모든 열 (loc, iloc)
iris.loc[[0,50,100],:]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [10]:
iris.iloc[::50,:]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [12]:
# 5. 0번째, 25, 50번째, 75번, 100번째, 125번째 행의 petal_length와 petal_width (loc, iloc)
iris.loc[::25,'petal_length':'petal_width']

     petal_length  petal_width
0             1.4          0.2
25            1.6          0.2
50            4.7          1.4
75            4.4          1.4
100           6.0          2.5
125           6.0          1.8

In [14]:
iris.iloc[::25,2:4]

     petal_length  petal_width
0             1.4          0.2
25            1.6          0.2
50            4.7          1.4
75            4.4          1.4
100           6.0          2.5
125           6.0          1.8

In [16]:
# 6. species가 versicolor인 데이터의 모든 열
iris[iris.species=='versicolor']
iris[iris['species']=='versicolor']
iris[iris['species'].str.contains('versicolor')]

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

In [19]:
# 7. species가 setosa인 데이터 최초 5개 행만 출력
iris[iris.species=='setosa'].head()
iris[iris['species']=='setosa'].iloc[:5]
iris[iris['species'].str.contains('versiolor')]
iris.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
# 8. sepal_length가 6.5이상인 데이터 최초 5개 행만 출력
# iris[iris['sepal_length']>=6.5]
# iris.head() ==>틀린답
iris[iris.sepal_length>=6.5].head()
iris[iris['sepal_length']>=6.5].iloc[:5]

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
58           6.6          2.9           4.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor

In [28]:
# 9. sepal_length가 7.2이상인 데이터의 'sepal_length'와 'sepal_width'와 'petal_length'
iris.loc[iris.sepal_length>=7.2,['sepal_length','sepal_width','petal_length']]

     sepal_length  sepal_width  petal_length
105           7.6          3.0           6.6
107           7.3          2.9           6.3
109           7.2          3.6           6.1
117           7.7          3.8           6.7
118           7.7          2.6           6.9
122           7.7          2.8           6.7
125           7.2          3.2           6.0
129           7.2          3.0           5.8
130           7.4          2.8           6.1
131           7.9          3.8           6.4
135           7.7          3.0           6.1

In [29]:
# 10. versicolor종중에서 sepal_length가 6.5보다 큰 데이터의 모든 열
iris[(iris.species=='versicolor')&(iris.sepal_length>6.5)]

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
58           6.6          2.9           4.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
86           6.7          3.1           4.7          1.5  versicolor