In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

# 1. 데이터셋 가져오기

In [19]:
import pandas as pd
url ='https://raw.githubusercontent.com/4aix/data/refs/heads/master/ch13_apt_fillna_median.csv'
df = pd.read_csv(url)
df.head()

  지역명   평당분양가격    연도   월
0  서울  18189.0  2013  12
1  부산   8111.0  2013  12
2  대구   8080.0  2013  12
3  인천  10204.0  2013  12
4  광주   6098.0  2013  12

- 지역명2 : 지역명필드를 라벨인코딩하여 추가
- 독립변수(x) : 지역명, 연도, 월
- 종속변수(y) : 평당분양가격
- 독립변수와 종속변수(reshape)의 스케일 조정
    * 정규화(MinMaxScaler) 작업후 : 지역명2m, 연도m, 월m 컬럼으로추가m =>df_m
    * 표준화(StandardScaler) 작업후 : 지역명2s, 연도s, 월s 컬럼으로추가s =>df_s
    =>지역명, 연도, 월, 지역명2, 지역명2m, 연도m, 평당 분양가격m, 지역명2S, 연도S,월S걸럼, 평당분양가격S
- 데이터 프래임.to_numpy(),데이터 프래임.values, np.array(데이터 프래임)등을 이용하여 데이터 프래임을 넘파이배열로 변환

# 2.  지역명의 라벨 인코딩

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['지역명2'] = le.fit_transform(df['지역명'])
df.head(17)

   지역명   평당분양가격    연도   월  지역명2
0   서울  18189.0  2013  12     8
1   부산   8111.0  2013  12     7
2   대구   8080.0  2013  12     5
3   인천  10204.0  2013  12    11
4   광주   6098.0  2013  12     4
5   대전   8321.0  2013  12     6
6   울산   8090.0  2013  12    10
7   경기  10855.0  2013  12     1
8   세종   7601.0  2013  12     9
9   강원   6230.0  2013  12     0
10  충북   6589.0  2013  12    16
11  충남   6365.0  2013  12    15
12  전북   6282.0  2013  12    13
13  전남   5678.0  2013  12    12
14  경북   6168.0  2013  12     3
15  경남   6473.0  2013  12     2
16  제주   7674.0  2013  12    14

# 3. MinMaxScaling

In [25]:
from sklearn.preprocessing import MinMaxScaler
x=df[['지역명2','연도','월']]
y=df[['평당분양가격']]

scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

x_m = x_scaler_m.fit_transform(x)
y_m = y_scaler_m.fit_transform(y)

df_m = df.copy()
df_m[['지역명2m', '연도m', '월m']] = x_m
df_m['평당분양가격m'] = y_m

df_m.head()

  지역명   평당분양가격    연도   월  지역명2   지역명2m  연도m   월m   평당분양가격m
0  서울  18189.0  2013  12     8  0.5000  0.0  1.0  0.328198
1  부산   8111.0  2013  12     7  0.4375  0.0  1.0  0.065274
2  대구   8080.0  2013  12     5  0.3125  0.0  1.0  0.064466
3  인천  10204.0  2013  12    11  0.6875  0.0  1.0  0.119878
4  광주   6098.0  2013  12     4  0.2500  0.0  1.0  0.012757

# 4.StandardScaling

# 5.지역명을 원핫인코딩